# Generated by Django 4.1.7 on 2023-02-26 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ansorapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="phoneotp",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ansorapp.courses",
                verbose_name="Course type",
            ),
        ),
        migrations.AddField(
            model_name="phoneotp",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Applicant Full Name"
            ),
        ),
        migrations.DeleteModel(name="Applicants",),
    ]
